<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class GeneratePackageSlugs extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'packages:generate-slugs';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate slugs for existing packages';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $this->info('Generating slugs for existing packages...');
        
        // Get the Package model
        $packageModel = app(\App\Models\Package::class);
        
        // Get all packages without slugs or with empty slugs
        $packages = $packageModel->whereNull('slug')->orWhere('slug', '')->get();
        
        $count = 0;
        
        // Process each package
        foreach ($packages as $package) {
            // The slug will be auto-generated by the model's boot method
            $package->save();
            $count++;
            
            $this->line("Generated slug '{$package->slug}' for package '{$package->title}'");
        }
        
        $this->info("Completed! Generated slugs for {$count} packages.");
        
        return 0; // Success
    }
}
