<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class GenerateServiceSlugs extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'services:generate-slugs';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate slugs for existing services';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $this->info('Generating slugs for existing services...');
        
        // Get the Service model
        $serviceModel = app(\App\Models\Service::class);
        
        // Get all services without slugs or with empty slugs
        $services = $serviceModel->whereNull('slug')->orWhere('slug', '')->get();
        
        $count = 0;
        
        // Process each service
        foreach ($services as $service) {
            // The slug will be auto-generated by the model's boot method
            $service->save();
            $count++;
            
            $this->line("Generated slug '{$service->slug}' for service '{$service->title}'");
        }
        
        $this->info("Completed! Generated slugs for {$count} services.");
        
        return 0; // Success
    }
}
